// DO NOT EDIT THIS FILE. This is a fully complete implementation.
package main

import (
	"fmt"
	"net/http"

	"github.com/droxey/goslackit/slack"
	// "github.com/joho/godotenv"
)

// main is our entrypoint, where the application initializes the Slackbot.
func main() {
	// err := godotenv.Load()
	// if err != nil {
	// 	log.Fatal("Error loading .env file")
	// }
	// port := ":" + os.Getenv("PORT")
	go http.ListenAndServe("4000", nil)
	slackIt()
}

// slackIt is a function that initializes the Slackbot.
func slackIt() {
	// botToken := os.Getenv("BOT_OAUTH_ACCESS_TOKEN")
	// fmt.Println(botToken)
	slackClient := slack.CreateSlackClient("xoxb-47155861858-566989616759-yxZOERbTuTk544LWY2FvQTvB")
	fmt.Println(slackClient)
	slack.RespondToEvents(slackClient)
}
